export const DbVars = Object.freeze({
    CultureId: 'CultureId',
    StatusId: 'StatusId',
    UserId: 'UserId',
    Files: 'Files',
    Id: 'Id',
    ID_: 'ID_',
    StatusRoleId: 'StatusRoleId',
    AuthUser: 'AuthUser',
    ActionFranchiseId: 'ActionFranchiseId',
    ActionServiceTypeId: 'ActionServiceTypeId',
    ActionMode: 'ActionMode',
    ActionTypeId: 'ActionTypeId',
    ActionMasterId: 'ActionMasterId',
    ProfileId: 'ProfileId',
    profileid: 'profileid',
    trainerId: 'trainerId',
    MasterId: 'MasterId',
    DocTypeId: 'DocTypeId',
    docpath: 'docpath',
    UserData: 'userData',
    TODAY: 'TODAY',
    DAYS_7: 'DAYS_7',
    DAYS_14: 'DAYS_14',
    DAYS_31: 'DAYS_31',
    TOTAL: 'TOTAL',
    Remarks: 'Remarks',
    enUS: 'en',
    arAE: 'ar',
    Description: 'Description',
    ACTION_TYPE: 'ACTION_TYPE',
    SERVICE_BASE_NAME: 'SERVICE_BASE_NAME',
    LOGIN_ROUTE: 'login',
    DASHBOARD_ROUTE: '/dashboard',
    ACTIONLIST_ROUTE: '/actionlist/myactions',
    BM_ACTIONLIST_ROUTE: '/bmactionlist',
    INCD_ACTIONLIST_ROUTE: '/incidentactionlist',
    LINE_ID: 'LINE_ID',
    SESSION_KEY: '9074W2K3ITC21_Data',
    TAXI_NUMBER: 'TAXI_NUMBER',
    REF_CHASIS_NUMBER: 'REF_CHASIS_NUMBER',
    REF_VEHICLE_MAKE: 'REF_VEHICLE_MAKE',
    REF_VEHICLE_MODEL: 'REF_VEHICLE_MODEL',
    IS_CANCEL_REPLACE: 'IS_CANCEL_REPLACE',
    REGISTRATION_DATE: 'REGISTRATION_DATE',
    REG_EXPIRY_DATE: 'REG_EXPIRY_DATE',
    visible: '[visible]',
    groupIndex: '[groupIndex]',
    VEHICLE_ID_: 'VEHICLE_ID_',
    VEHICLE_ID: 'VEHICLE_ID',
    DATA_CHANGED_EVENT: 'dataChangedEvent',
    RELOAD_DATA_EVENT: 'reloadDataEvent',
    STATUS_TYPE_ID_: 'STATUS_TYPE_ID_',
    SERVICE_BASE_: 'SERVICE_BASE_',
    TRANS_ID: 'TRANS_ID',
    ARTICLE_ID: 'ARTICLE_ID',
    AccountId: 'AccountId',
    TRANS_ID_: 'TRANS_ID_',
    DEVICE_ID: 'DEVICE_ID',
    CANDIDATE_ID_: 'CANDIDATE_ID_',
    FRANCHISE_ID: 'FRANCHISE_ID',
    CORRELATIONID: 'correlationId',
    REGION_ID: 'REGION_ID'
    // SERVICE_TYPE_: 'SERVICE_TYPE_',
    // VEHICLE_TYPE_: 'VEHICLE_TYPE_',
    // OPR_REGION_ID_: 'OPR_REGION_ID_',
    // STATUS_ID_: 'STATUS_ID_', 
    // IS_SCHEDULING_REQUIRED_: 'IS_SCHEDULING_REQUIRED_'
});

export const ConstParams = Object.freeze({
    Trans_Id: 'TransId',
    Master_Id: 'MasterId',
});
export const Procedures = Object.freeze({
    FRM_TRANS: {
        USER_LOOKUP_SPR: 'FRM_TRANS.USER_LOOKUP_SPR', 
    }
});
